title: "Quick and clean: advanced Python for data science in biology"
baseurl: /workshop_adv_python

# where things are
# where things are
layouts_dir: ./workshop-commons/layouts
includes_dir: ./workshop-commons/includes
sass:
  sass_dir: ./workshop-commons/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: overview
  - title: Schedule
    url: schedule
  - title: Syllabus
    url: syllabus
  - title: Reading materials
    url: reading_materials
  - title: Practical information
    url: practical
  - title: Contact
    url: contact

theme: jekyll-theme-minimal
